# Generated by Django 2.2 on 2020-07-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200715_2218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set(),
        ),
    ]
