# Generated by Django 2.2 on 2024-03-01 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20200716_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='商品id', on_delete=django.db.models.deletion.CASCADE, related_name='goods_favs', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='userfav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
